name: keebie
version: 0.0.1
summary: More keyboards = faster hacking
description: Keebie is a small script for assigning and executing commands on a theoretically unlimited number of keyboards. So you can make the spacebar search for a window and paste something. Or make the M button run a script.

base: core20
grade: stable
confinement: strict

architectures:
  - build-on: amd64
    run-on: amd64

parts:
  keebie:
    plugin: make
    source: https://github.com/robinuniverse/Keebie.git
    stage-packages:
      - python3
      - python3-evdev
      - inotify-tools
    override-build: |
      make install

apps:
  keebie:
    command: keebie
    plugs:
      - raw-input
